### ISSUE TITLE
Create .Buf/.Blob coercers on Cool

### ISSUE THREAD

**Issue by lizmat** [Raku/problem-solving#16]
This would create a `Buf`/`Blob` of the `Int` of the given value, for the correct size, big endian.

**Comment by AlexDaniel** [comment]
OK, but which problem is this going to resolve?

**Comment by jnthn** [comment]
What @AlexDaniel said: we should start with the problem. I speculate the problem is:

* It's tiresome to write `my Buf $x .= new; $x.write-int32(42);` to get a `Buf` containing the encoding of that integer value
* There's no ideal way to get a `Blob` rather than a `Buf` if wanting to have it as an immutable value

Those are probably fair problems, thought the solution proposed here doesn't seem ideal to me, since:

* Things like `Str` are also `Cool`, and having that be numified in response to `.Buf` or `.Blob` feels a bit odd. Folks would quite possibly expect it to do something like `.encode` does.
* There is no "correct size" for the integer 1. Depending on the needs of the binary format being produced, it could be represented in 1 byte, 2 bytes, 4 bytes, or 8 bytes.

I'd be more in favor of factory methods on `Blob`/`Buf`, so you could do `Blob.from-int32(-1)` and it'd produce a 4-byte `Blob` holding the representation of `-1`; endianness can optionally be provided as it is in `write-int32`.

**Comment by lizmat** [comment]
That'd work for me too  :-)

**Comment by CurtTilmes** [comment]
While you're at it, how about taking an array (Iterable) as input as well?

**Comment by jnthn** [comment]
@CurtTilmes Perhaps, but we have to be a bit careful, in that arrays in numeric contexts typically numify. It'd not be unreasonable for somebody to write `my $chunk-count = Blob.from-int32(@chunks)` and expect to have a `Blob` with the number of elements in the array encoded. It's a natural generalization for anyone happily doing `if @stuff == 1 { }` and similar.

Maybe a plural version of the methods: `Blob.from-int32s(@values)`?

**Comment by CurtTilmes** [comment]
Sounds good.  I like this because it makes a few things easier.

Native types, shaped arrays, Blob-ifying numbers, etc. are on their way to competing with [NumPy](https://www.numpy.org/) and [PDL](http://pdl.perl.org/), but I still don't understand how it all fits together.
