### ISSUE TITLE
What should unicode subscripts do? (and should they do anything at all?)

### ISSUE THREAD

**Issue by AlexDaniel** [Raku/problem-solving#183]
Basically, what should be the meaning of `$x₂`, and should the compiler even allow that by default or should it be left for modules to take care of.

This is one of the most commonly requested unicode features. See https://github.com/rakudo/rakudo/wiki/save-me-from-ASCII#subscripts for the discussion of the options.

**Comment by JJ** [comment]
No meaning, same as ', _ or 3 have no meaning. It's just an allowed symbol, that typographically helps you identify the object of the variable.

**Comment by AlexDaniel** [comment]
But `$x²` on the other hand acts like an op, so why not `$x₂` or especially `@x₂`?

**Comment by JJ** [comment]
OK, I see what you mean. The problem is that it makes sense with @, not so much with % or $. To avoid ambiguity, maybe just use as a simple character. 
Another option would be making it a bit more like x::<2>. That way you would be able to iterate over them. But then the syntax would become a bit wonky, using variable names as subscripts... And you would be creating a namespace out of nowhere... So no, really. Best to make them have no meaning.

**Comment by AlexDaniel** [comment]
But in some sense it means just as much for `$x`. Here:
```raku
my $x = <a b c d>;
say $x[2]
```
Output
```
c
```
I think it's rather intuitive that subscripts are used array subscripts. When people suggest that they should be part of the literal they typically want to use them for exactly the same purpose, just without creating an array first.

🤷

**Comment by alabamenhu** [comment]
> When people suggest that they should be part of the literal they typically want to use them for exactly the same purpose, just without creating an array first.

Perhaps, but often they're used as a sort of extended identifier (and we can use subscripted letters for that purpose now, I've cheated and used subscript-O for to mean "initial value").  While sometimes they do have a listy meaning, I see them frequently used in contexts that feel far more scalar-like than array-like.  They also can be used with functional meaning (so more equivalent to `()` than `[]`).  Then you've got chemical: `CO₂` makes sense as an identifier to me, but definitely isn't listy.

That said, either way works for me, because it should be easy enough to use a module for the other case — and that's better than the status quo of needing a module in all cases

**Comment by jnthn** [comment]
> This is one of the most commonly requested unicode features

Citation needed. :-)

> But $x² on the other hand acts like an op, so why not $x₂ or especially @x₂?

Superscripts not only act like an op, but really *are* a postfix op, grammar wise. I was pondering an answer like "because people understand the meaning of the superscripts from their everyday encounter with them in mathematics as meaning raise to a power, but" - then found I wasn't really sure what to write next, because:

1. I'm actually not sure subscripts *are* encountered anything like so commonly.
2. When they are, their usage is then far more domain specific.

I mean, if you ask me the last time I wrote a subscript integer, it'll probably be when I was scribbling out some code in SSA form, where they represent different versions of the same variable (which is absolutely *not* an array indexing operation). If it's a chemistry context, well, the examples are already here. But would folks working in the chemistry domain want them as just a name, or to construct objects representing a molecule with the appropriate components? The mathematical use of it for indexing a set of things, and thus the idea of having it as an array indexer, isn't unreasonable either - just no more reasonable than any of the other interpretations.

> that's better than the status quo of needing a module in all cases

Except that if we leave the syntax free for the taking it's *easy* for slangs to take it, without having to first go back and make identifiers not swallow it first, which they would. Also, there's probably a bit more of a stigma to changing the meaning of something that the main language already has a meaning for - and rightly so, in so far simply adding a `use` of a module and having existing code broken isn't particularly desirable (unless it's expected, such as a module that introduces a stronger type-checking regime).

Also, I'm a bit nervous about introducing a new special list of things that can be part of any identifier. There's of course a slight performance angle on it - identifiers are one of the most common things we parse - but also that we otherwise define what can go into an identifier in terms of Unicode properties, and I'd prefer it remains that way. (Yes, hyphen/apostrophe are explicitly mentioned, but I don't think anyone is asking for subscripts as an identifier part separator).

Thus, I feel we should leave subscripts to the language extensions, which can afford to be domain specific in a way the general purpose core language cannot.
