### ISSUE TITLE
Should Rakudo fail at compile time if it's possible?

### ISSUE THREAD

**Issue by JJ** [Raku/problem-solving#191]
This comes from [this old issue](https://github.com/Raku/old-issue-tracker/issues/1455): two routines with the same signature will still fail at runtime, not at compile time. 

[@masak ](https://github.com/Raku/old-issue-tracker/issues/1455#issuecomment-624974691) mentions other cases in the comment. Should this be a rule "Fail at compile time if at all possible"?

**Comment by jnthn** [comment]
> "Fail at compile time if at all possible"

That's probably a bit too strongly stated. If the analysis required to make something fail at compile time makes compile times ten times longer, then while it may be possible, it's probably not very desirable. Of course, such cases are the exception, not the norm.

Certainly there are many more things in the lexical part of the language that we can detect at compile time, and it'd be good to move in that direction. However, such things need to be introduced at language version boundaries, or we risk breaking modules that had mistakes on rarely taken code-paths. Of note, the request in the ticket with regards to multi sub duplicates being detected at compile time, or the invalid use of `return`, seem entirely reasonable requests; it's just a case of getting round to doing them. (I'm hopeful some of these may become easier with RakuAST. We'll see.)

Closing because I'm not sure there's any immediate follow-up action here (the linked issue remains open and valid), and I think I've answered the question.
