### ISSUE TITLE
What action should be taken in response to AlexDaniel's behavior with other developers

### ISSUE THREAD

**Issue by lizmat** [Raku/problem-solving#238]
After having been responsible for having Jonathan Worthington leave the Raku project (hopefully only temporarily), he continues his efforts to force a complete re-design of the Raku language, in an effort to make it simpler and faster.  But instead of actually being constructive and actually writing PR's for this, he just wants to "debate" this.

This "debating" is in fact sealioning.  And I'm sick of it, as jnthn has been.

After the discussion around https://colabti.org/irclogger/irclogger_log/raku-dev?date=2020-10-13#l162 , I have come to the conclusion that he is a net **NEGATIVE** influence on the Raku project.  He does not seem to understand that an open source projects is run by volunteers, and that chasing away volunteers is the best way to kill a project.

He appears to think that losing the main architect of a project is "too bad".

I think it's too bad that AlexDaniel, who has done amazing things for Raku in the past, has turned this negative and this toxic.  But it's come to the point that I'm seriously considering leaving the Raku project because of him, and *that* is something I dearly do *not* want to happen.

**Comment by lizmat** [comment]
For reference: AlexDaniel has already been banned from the MoarVM repo as well as from the #moarvm IRC channel.

**Comment by samcv** [comment]
From what I have read, these conversations have gotten nowhere and haven't subsided despite AlexDaniel being told they aren't productive.

I think it's important (and I think @lizmat was very clear in separating these), that the technical concerns of AlexDaniel are separate from the way he is conducting his discussions about it. But we can see a clear effect from it if jonathan did indeed leave for this reason.

Maybe a removal for a set period of time would benefit the community? Such as a one month removal from IRC (possibly github, though I'm not sure the logistics and scope of how that works).

**Comment by AlexDaniel** [comment]
> a complete re-design of the Raku language, in an effort to make it simpler and faster

That's actually a good summary. It has been almost 5 years since the first language release, during which the majority of publicly mentioned speedups were gained through rewriting Rakudo code in NQP. I want Raku to be successful but at that pace I'm afraid it won't get far. Looking at the [benchmark](https://tux.nl/Talks/CSV6/speed4.html), actual performance has been indeed stagnant for the last two years, yet Rakudo is still not fast enough compared to other popular languages (and especially performance-oriented languages that push the bar even higher).

The idea of creating a new compiler isn't exactly new or surprising. Here's [one example](https://andrewshitov.com/2019/10/12/ok-raku/) of it being proposed. From that article:

> This is the only way Raku can prosper and thrive. 

I laughed at it at the time, but now I start to understand that it is indeed the case. However, compilers are not fully disconnected from the languages they implement, as some like to think. Design decisions of the language (and especially bad ones) really affect and limit what the compiler can possibly do. Therefore lately I've bringing up a wide variety of topics, mostly about what Raku can be in the future (and how it can get away from decisions of the past).


> Maybe a removal for a set period of time would benefit the community? Such as a one month removal from IRC (possibly github, though I'm not sure the logistics and scope of how that works).

Look, over the years I've gained a lot of privileges that I only used for good, there was never a complaint about any misuse. First my admin rights were removed from MoarVM, then later I was banned completely, which again didn't achieve anything useful, especially given that I routinely use most of the given privileges for a variety of housekeeping tasks. If that continues then it'll just limit the useful things I do, at which point it's much easier for me to leave which is what @lizmat seems to want so badly.

**Comment by lizmat** [comment]
>  for me to leave which is what @lizmat seems to want so badly.

At this point, I regret to say, that is *exactly* what I want.  It is also in the title of this issue, I'm glad you caught that subtlety.

**Comment by AlexDaniel** [comment]
I didn't make it clear in the previous comment – temporary action is not an option here. If you want to exclude a member of the community for their opinions, that's totally fine for me.

**Comment by vrurg** [comment]
With a heavy heart, I have to fully agree with Liz. @AlexDaniel, you really do more harm than good now. You really miss the point that in an fully open source project the one who pushes an idea is the one to implement it, with only few exceptions. You really chosen one the most annoying forms of pushing your ideas. The last few months I hardly have time to follow IRC and this probably spares me from most of the negative discussions happening over there. But even then I see too many complains of yours.

You think Rakudo moves into wrong direction? Fork it and show how to do things right.

**Comment by samcv** [comment]
@AlexDaniel We are only able to control the action we take, we have no control over the action you choose to take. Saying a temporary action will cause you to leave permanently, while I don't doubt what you say, feels like an attempt to change the decision making here. I will be clear: this should not be part of our decision making.

**Comment by ggoebel** [comment]
The [RSC Code](https://github.com/Raku/Raku-Steering-Council/blob/main/papers/Raku_Steering_Council_Code.md) references a **Code of Conduct**. But that code does not yet exist and has not been voted upon by the RSC.

The [RSC Code](https://github.com/Raku/Raku-Steering-Council/blob/main/papers/Raku_Steering_Council_Code.md) provides two mechanisms: 

- [Ejecting core team members](https://github.com/Raku/Raku-Steering-Council/blob/main/papers/Raku_Steering_Council_Code.md#ejecting-core-team-members)
- [Vote of No Confidence](https://github.com/Raku/Raku-Steering-Council/blob/main/papers/Raku_Steering_Council_Code.md#vote-of-no-confidence)

It does not provide for temporary sanctioning, censure, etc. However, removing someone from the core team does not prohibit them from contributing or being voted back into the core team at a later date.

We are all responsible for our tone and conduct on in communications. I hope that the Raku Code of Conduct will lean heavily on positive behavioral supports and interventions and continue to be a humble welcoming troll hugging environment per Audrey Tang's [Lessons Learned From Open Source Communities](https://medium.com/@audrey.tang/lessons-i-ve-learned-32f5d8107e34).

I think the path forward is for either:

- RSC to vote to eject core member(s)
- core team to call a vote of no confidence against RSC member(s)

Either way, the outcome of such a vote will clarify the community's position with regards to code of conduct until such time as a formal code of conduct is adopted.

**Comment by AlexDaniel** [comment]
Oh, one more thing. You probably want to have the IRC ban delayed so that people are able to request any info they may need.

**Comment by niner** [comment]
@AlexDaniel I'd like to repeat here officially what we have told you many times: this has never been and is still not about any of your opinions. It has always been about how you express those. It's about disrespect, complete disregard of community member's feelings and about a destructive style of discussion where you state opinions as facts and ignore opposing views.

It's really sad. I value your actual contributions to Raku highly and I am sure that others do so as well. I also love the Raku community and it hurts me to see it falling apart because of the actions of a single member. None of our strategies to resolve this have succeeded. We are simply running out of ideas and the only means left to protect this community seems to be to exclude you from it. How would you solve this if you were in my place?

**Comment by AlexDaniel** [comment]
> I'd like to repeat here officially what we have told you many times: this has never been and is still not about any of your opinions. It has always been about how you express those.

You came up with a proposal that before I post anything I'd first give it for a review to you. I agreed, and we tried that. Immediately it became very clear that it's not the way I say things, but what I'm saying that bothers you and others (as in you tried to rewrite the actual message, not the tone of it, or anything like that). This isn't that surprising, for example, let's say (I know you might not agree, but let's say for the sake of the argument) that MoarVM won't get us far in the future and something else needs to be created. Is there any sugar-coated way of proposing that which wouldn't drive nuts existing developers who have put years of work into it? I don't think there is, as the whole situation is inherently unfortunate and sad. The only way that keeps getting proposed is that you go, spend many many hours doing it, and then… something? I personally don't think that expecting a single person, with the current state of things, to do something like that is realistic, which is why I proposed to start a group effort trying to achieve that. However, jnthn made it clear that whatever happens, it can not be associated with “Raku”, and Raku channels can't be used to organize that work. Hm. 

By the way, almost immediately after that review interaction I had with you, you felt fine giving [this response](https://github.com/perl6/rakudo.org/issues/50#issuecomment-696821098) (which not only has an unacceptable condescending tone, but is also plainly wrong) to one of the users. You can definitely find examples when I got on the nerves of the devs (by *saying* things), but I don't recall doing anything like that to users. But that situation is actually a very consistent behavior coming from the Raku community, the toxicity is fine when it flows outwards (e.g. framing people outside the community who provide criticism as trolls), or when it comes in defense of Raku.

> How would you solve this if you were in my place?

Well, there's RSC where we can discuss the project direction, among other things. There are clearly opposing views regarding that. Once that's sorted, maybe there will be less beef between members.

**Comment by AlexDaniel** [comment]
> No, it isn't.

How about this ticket with its attempt to be SEO-friendly? :) Fixed now, nevermind.

> As answers go, this is a bit on the evading side. Yes, we can discuss it
within the RSC. But what is the solution you yourself propose?

People can be very attached to things (that's OK), and as a result can get very defensive while some open-mindedness can be beneficial. We had a similar situation in case of “Raku” alias where all hell broke loose, only to agree on a full rename later once the damage was already done. It was all about some very practical aspects, except that things got way too personal. All I'm trying to instigate is having a shared realistic view on what Raku is today and what it can be in the future, and later figuring out a way to fast track it to that. The discussion we are having right now where people are very offended because of me pointing out some issues in the language/compiler might not even be relevant in the future. Or maybe not.

**Comment by AlexDaniel** [comment]
> What are the concrete steps you propose (who does what and when)? How will they lead to jnthn and lizmat (and me for that matter) feeling safe and secure in the Raku community and having fun contributing? I don't see how a strategy for the product will effect this. What steps to you propose to heal the wounds?

That isn't something that is possible to guarantee or plan. For example, lizmat's behavior was extremely unacceptable during the alias situation, including targeted personal attacks against a developer. Now lizmat seems to be insisting (as shown by the title change above) that a search for both my nickname *and* name brings this ticket for people who might not even have the background information regarding the state of the project and the whole situation in general. I don't know of a solution that would keep the person behaving this way but at the same time prevent that behavior. Why any of that is continuously considered acceptable in this community is completely beyond me. Have you seen me attacking a person I don't agree with, rather than simply expressing my disagreement? Because you seem to mention “safe and secure”, can you elaborate?

As for jnthn, I'm sure we can find common ground to coexist peacefully. But, hypothetically, if RSC decided to change project goals significantly, who's to guarantee that jnthn will be comfortable to remain in the project?

**Comment by tony-o** [comment]
The title of this issue is both bad for raku and the inappropriate forum.  See (X vs XY)[https://github.com/Raku/problem-solving#reporting-a-problem], this issue assumes the Y rather than discussing the problem itself and has become both an eyesore and off topic.

This issue should be closed and handled within the RSC.  Actual CoC violations (see #131) would probably move this discussion forward.

See #131 for another example of this type of discussion being unproductive in this forum.

**Comment by niner** [comment]
Agree with tony-o. Is it possible to delete an issue ticket? This discussion has never belonged here.

**Comment by AlexDaniel** [comment]
@vendethiel that might be true, please bring it to my attention (I'm AlexDaniel on IRC, or you can do it here if you insist).

**Comment by AlexDaniel** [comment]
> Agree with tony-o. Is it possible to delete an issue ticket? This discussion has never belonged here.

Yes, but it has to be enabled in repo settings. I have enabled it now but will leave it to somebody else (anybody with admin right) to pull the trigger.

**Comment by samcv** [comment]
> The title of this issue is both bad for raku and the inappropriate forum. See [X vs XY](https://github.com/Raku/problem-solving#reporting-a-problem), this issue assumes the Y rather than discussing the problem itself and has become both an eyesore and off topic.

Agreed and I have changed the topic.

> This issue should be closed and handled within the RSC.

The RSC has the power to enforce or CoC for the Raku community. Though Raku does not have its own CoC, and the Perl Foundation has not yet adopted a CoC, though we had one for the last conference. I am on the Community Affairs Team for the Perl Foundation which for example handles CoC issues. I am more than willing to work with the RSC team on this. I will reach out to everyone on this. I am going to close this now.

**Comment by AlexDaniel** [comment]
@samcv just in case, there's an open PR [here](https://github.com/Raku/problem-solving/pull/136) which I looking forward to accepting.

**Comment by samcv** [comment]
Also, anyone who has already posted and those who have not posted, can you please send the Community Affairs team an email at community-affairs@perlfoundation.org Noting specific behaviors, as well as impact on others in the community is appreciated, but we will accept any information you choose or do not choose to provide.

All emails will be completely confidential with the community affairs team of the Perl Foundation. By default we won't share the text or your identity with the RSC, as it's not part of the community affairs team. You can also indicate if you would like to, or not share your identity and or parts or all of your message with the RSC.
