### ISSUE TITLE
How should modules/distributions be handled when severe security issues are discovered?

### ISSUE THREAD

**Issue by ugexe** [Raku/problem-solving#244]
How should different groups (ecosystem, tooling, core, etc) handle insecure code that is being distributed through community / default channels?

I bring this up having discovered a tool in the ecosystem that is subject to shell injection and thus running arbitrary code... in this case it is when checking a dependency from a META6.json in any ecosystem (i.e. `"depends" : [";top:from<native>"]` launches `top`).

**Comment by codesections** [comment]
This is definitely something we should decide/address – I'm glad you opened this issue.

#229 might be a subset of this issue, in that (like the code execution method mentioned above) it's a security issue that arises out of the ecosystem and tooling rather than from a single package.

**Comment by ugexe** [comment]
The linked issue is quite different in that the solution can easily be automated. In this case we have a specific, single, package that uses poor programming practices (which is a problem once someone starts encouraging others to use it) and  not handling things in a safe way -- there is no reason a native dependency can't be called `;top:from<native>` afterall and an ecosystem can't possible know what native dependencies names allow since they are outside the scope of raku.

(of course context is important as well... a tool that downloads and runs code is going to have plenty of code injection avenues -- just put malicious code in the module itself. However, in this case the exploit can happen at a point where the user would not expect external code to be executed)

In other words: a package that is not malicious itself can still be negligent in a way that easily opens users up to a malicious actor.

**Comment by JJ** [comment]
I would opt for retiring it from the ecosystem.

**Comment by hythm7** [comment]
I would say remove the distribution from the Ecosystem and throw it into a volcano. Not really, I'm joking!

Here is what I would do if I discovered a security issue in a module in the ecosystem. I will write that as a short story:

Say I like this module ([Pakku](https://github.com/hythm7/Pakku)), and started reading the code, (Reading for fun of course, not hoping to find issues). While I'm enjoying reading the wonderful code, oops suddenly I stumbled upon a security bug :-( What should I do now!.

Looking a little bit more at the bug, wait a second, it is actually very similar to the one described here in this issue, or may be it is actually the one this issue is referring to!.

Looking a couple more seconds into the issue, and the fix is obvious (typing exactly 8 characters).

Because I genuinely care for fixing security issues and of course because I like the module, I thought I can do one of these options:

- Open an issue in the distribution repo
- Create a PR with the fix
- Inform the author about the issue if possible


And because I like the module, I created a [PR](https://github.com/hythm7/Pakku/pull/12) in less than a minute and felt good because now the security issue that bothered me is fixed :-)

Sorry to bore you with that short story, anyway to summarize, I think what we should do in case of finding modules in the ecosystem that have severe security issues (or any other issues for that matter) is to try to fix the issue, create issue in module repo or inform the author. oh wait, that is pretty much what is done when someone finds an issue, I think!, but never mind, I'm curious to see what other solutions might be, May be throw the distribution into a volcano and the joke wasn't a joke after all!

Anyway I like this issue because it helped me identify and fix a very basic shell injection issue that somehow went unnoticed. Thanks ugexe for helping me improve Pakku <3.

**Comment by ugexe** [comment]
For the record I did not name what module or make the exploit known to the public because 1) doing so would give away a live exploit that other people may still have exposed on their system and 2) this issue was about the general case.

It’s a bit concerning you are so dismissive of this issue just because you’ve been at the wrong end of it though.

**Comment by ugexe** [comment]
> And because I like the module, I created a PR in less than a minute and felt good because now the security issue that bothered me is fixed :-)

But that PR wasn't valid, and misleads others into believing the issue is fixed when its not -- it just means now `";top;":from<native>` launches top, the exploit is publicly exposed while still live to the public, and users trust in future security related fixes will potentially decline.

**Comment by hythm7** [comment]
That will be fixed too, I'm glad you spend time helping improving Pakku :-)

**Comment by ugexe** [comment]
Can we not turn this into self promotion for Pakku and focus on the issue?

**Comment by hythm7** [comment]
> > And because I like the module, I created a PR in less than a minute and felt good because now the security issue that bothered me is fixed :-)
> 
> But that PR wasn't valid, and misleads others into believing the issue is fixed when its not -- it just means now `";top;":from<native>` launches top, the exploit is publicly exposed while still live to the public.

In fact this is misleading,  I tried that and it doesn't launch top, it doesn't even  parse it because it is invalid JSON.

> Can we not turn this into self promotion for Pakku and focus on the issue?
I didn't promote Pakku before, not here in this issue, not anywhere else, But now I decided that I will start promoting Pakku.

for the record I had few interactions with you may be 3 or 4 times, non of them were pleasant. so I will be replying (if needed)  here in this issue, but will avoid interactions with you in the future. because no matter what it just doesn't feel pleasant.

**Comment by ugexe** [comment]
My previous interaction with you was suggest you credit code you were explicitly copying and taking credit for. You first tried to claim you didn't steal anything, and after proving that was false you remained upset that I dared point it out to begin with. But I digress...

I hope you realize that if you wanted to use that malicious payload you would escape the quotes when putting them inside of json. Perhaps less than 60 seconds is not sufficient time for considering the problem-space?

I think we need some sort of solution to prevent this type of security negligence from affecting general users. The best I can come up with is some sort of reputation-like system, but security specific.

**Comment by hythm7** [comment]
> My previous interaction with you was suggest you credit code you were explicitly copying and taking credit for. You first tried to claim you didn't steal anything, and after proving that was false you remained upset that I dared point it out to begin with. But I digress...

Misleading, again. What happened is, there are _KNOWN_ keys for META6.json ` name version auth source-url .......` and so on, around 20+ keys, what I did, instead of typing all the keys by hand  to save typing and time, I copied them from [here](https://github.com/ugexe/zef/blob/master/lib/Zef/Distribution.pm6#L6-L24),  Anyone would deal with META file will need to use the _SAME EXACT NAMES_. it's really very dishonest from you that you want make others believe I stole code from you, for being lazy to type something. I invite everyone to examine  all Pakku* modules and points to anything remotely similar or stolen from his.

I'm trying to find a link for that mentioned interaction, if anyone knows please let me know if it's possible to get the commit history from 'master' branch which was replaced by 'main' branch recently.

**Comment by lizmat** [comment]
As far as I know, zef is published under the Artistic License 2.0.  It is my understanding that that allows copying of anything in the distribution.  Without the need of needing to credit anything.

Yes, sure, if one copies something that was part of a considerable effort, it would be nice to get credit somehow.  But to enforce credit, one would need to change the license.

So can we please stop this?

**Comment by ugexe** [comment]
I've lost all interest in this.

**Comment by lizmat** [comment]
Other people might still be interested in this issue.

**Comment by AlexDaniel** [comment]
I think @ugexe is putting too many expectations on what developers are supposed to know. I'd say this particular issue is different because it's the language itself that failed the user.

[This very well known article](https://eev.ee/blog/2012/04/09/php-a-fractal-of-bad-design/) (“PHP: a fractal of bad design”) nowadays resonates with me on many different levels. One of the quotes from there:

> programming is a hilariously young discipline, and none of us have the slightest clue what we’re doing

I think there's some deep wisdom in that. A good language (made hopefully by those who have a clue, at least a bit) should prevent us (who usually don't have a clue, and that's OK) from doing stoopid things.

Here's the comment I left on the Pakku fix: https://github.com/hythm7/Pakku/commit/302edc5a62ba7618aac3749ff099b1b14c8d9131#commitcomment-44174155. There I mention how a Raku PR from 5 years could've prevented the issue.

> How should different groups (ecosystem, tooling, core, etc) handle insecure code that is being distributed through community / default channels?

I know this is not an answer you're looking for, but what I think Raku developers should do is try to figure out if the language itself could've prevented the bug. And it could have, at least in this case.

I've already said that `qqx` shouldn't exist, and maybe that would've been sufficient by itself. But here's how another language handles the same problem space:

https://docs.julialang.org/en/v1/manual/running-external-programs/ 

> A common pitfall when running external programs via a shell is that if a file name contains characters that are special to the shell, they may cause undesirable behavior

> How did the file name get quoted? Julia knows that file is meant to be interpolated as a single argument, so it quotes the word for you. Actually, that is not quite accurate: the value of file is never interpreted by a shell, so there's no need for actual quoting; the quotes are inserted only for presentation to the user.

**Comment by AlexDaniel** [comment]
Heh, https://github.com/Raku/old-design-docs/pull/102 is actually a fantastic read. Full of positive and humorous crankiness, yet very thorough and on point. Interesting view of Raku of the past. Too bad it didn't get far, it did have more chances back then than it does now (that was pre-v6.c!). That said,  it's not like it or an even better alternative can't be accomplished today (even though Debate & Denial club won that time around, and has been consistently winning since then, it isn't a reason for not being hopeful).

**Comment by ugexe** [comment]
Please open a new issue.
