### ISSUE TITLE
Clarify "On Behalf of Community"

### ISSUE THREAD

**Issue by ash** [Raku/problem-solving#268]
## Proposal

Stop saying that the Raku Steering Council is acting "on behalf of the Raku community".

 ## Problem

I am fine if the RSC makes key-stone decisions about Raku development and related things. I am not fine if they add the "on behalf of the Raku community" clause. This is not correct to call a decision of a small group as if the whole (well, also small, but still bigger) group decided that.

**Comment by JJ** [comment]
This is regarding what exactly? Just to clarify, the RSC was voted in, and we take decisions based on what everyone says in the problem-solving repo, and then we generally reach a consensus.

**Comment by ash** [comment]
https://github.com/Raku/problem-solving/pull/267/files#diff-c3ca02399d22e62d71b6fd5b2457869d02a4170d3ddcbe6ed9d019aa3c88670fR1

**Comment by JJ** [comment]
You know you can comment there too, right? You proposed something. We took everything *everyone* said. We reached a consensus. That's not what you wanted. You don't like that. That's fine. That does not mean that the RSC is not acting as a representation of the community, which we are by origin and also by taking in *all* opinions, and then some informed opinions.

**Comment by JJ** [comment]
Then, of course, it's a PR that can be discussed upon, approved or rejected by more people than are actually sitting as RSC members, and discussed upon. I would invite you to share your grievances there.

**Comment by ash** [comment]
OMG, "grievances" is not a word you'd use.

**Comment by niner** [comment]
> OMG, "grievances" is not a word you'd use.

Please keep in mind that almost none of us is a native speaker of English. 
Languages are hard. That's why I am also confused by this ticket. I looked at 
2 dictionaries and "on behalf of" seems to mean the right thing. The RSC's 
work is meant to be for the benefit of the Raku community. The RSC's members 
were also elected by that community to represent them. The usage looks correct 
to me?

**Comment by ash** [comment]
Define the community then please.

**Comment by JJ** [comment]
@ash I was trying to be formal, but apparently failed. Changed to "issues". Point stands, however. If this is a general issue, let's continue here. If it's an issue you have with the wording of that PR, please let's do it there.

**Comment by sjn** [comment]
@ash, Is the question in this issue concerning a clarification around what mandates the RSC has, and/or how it received them?

**Comment by codesections** [comment]
> proposal: Stop saying that the Raku Steering Council is acting "on behalf of the Raku community".

The only statement in the linked PR that the RSC said it took "on behalf of the Raku community" was to thank you for bringing up this issue.  I've just added a commit that clarifies that we are personally thanking you, rather than thanking you on behalf of the community.

To address the larger issue: The RSC could have, consistent with its powers under the [Raku Governance Code](https://github.com/Raku/Raku-Steering-Council/blob/main/papers/Raku_Steering_Council_Code.md), simply voted on a course of action and carried it out.  However, that same code also encourages the RSC to "seek consensus among contributors and the core team before acting in a formal capacity".  Accordingly, the RSC decided _not_ to take any formal action.

Instead, we are addressing the decision through the normal Problem Solving process, as outlined in the [README](https://github.com/Raku/problem-solving/blob/master/README.md).  Under that process, one member of the community proposes a solution; the community then discusses that solution; and the solution is accepted if it is approved by all the reviewers listed in the README (currently 14).  Solutions can also be accepted without approval from all 14 reviewers if consensus exists in favor of the solution and two weeks have passed (again, as described in the README).  This consensus-driven process that, though not requiring unanimity, allows the community to act as a body.

So when the PR says that "the Raku community would like to formally request that Yet Another Society create a 'doing-business-as' for YAS", it is referring to going through this consensus process – a process in which the RSC plays no special role.  I am sorry if that wasn't clear from the language in the PR.  I suggested that language, so if it was confusing please blame me rather than @lizmat.

**Comment by ash** [comment]
Let me be as clear as I can.

1. The issue 263 reflects my opinion on the subject. I thought the community may benefit from it, but I did not claim I was doing that on behalf of the community.
2. During the TPF call, a representative of the RSC said that "the Raku community is asking YAS to make a DBA". That was said before any agreements in the above ticket.
3. The ticket was closed for comments quite soon after it was forcibly reopened.
4. There were comments from people who represent Perl, not Raku.

I may conclude that nothing tells that the decision is based on the "community request". 

This is fine, though. I just don't want my name, RSC and "on behalf of community" to be in one sentence. This is totally misleading, as it neither reflects my opinion, nor my opinion reflects the community wishes, nor the RSC decision answers any community's request. This is *not* the voice of the community.

**Comment by lizmat** [comment]
I'd rather be coding  :-(

**Comment by lizmat** [comment]
@ash:

> This file provides a solution to [issue #263 - The Raku Foundation](https://github.com/Raku/problem-solving/issues/263) by *Andrew Shitov*.  The members of the RSC (Raku Steering Council) would like to personally thank *Andrew* for creation of this issue, and the discussions it has brought.

Are you happy with this description?  If so, could you close this issue then?  If not, tell us what you would like to have changed?

**Comment by ash** [comment]
Thanks for changing the words, for sure. Although, I have a strong belief that this is a bigger issue, not just some random words I did not feel comfortable with. Say, the rest of the text is unchanged, and the items listed in https://github.com/Raku/problem-solving/issues/268#issuecomment-786464620 are there. But please let's do not continue on this.
