### ISSUE TITLE
The PS-process' acceptance policy doesn't match reality

### ISSUE THREAD

**Issue by patrickbkr** [Raku/problem-solving#272]
… or the other way round.

[This comment](https://github.com/Raku/problem-solving/pull/271#issuecomment-791286741) and the following few is the latest example.
[The process](https://github.com/Raku/problem-solving#acceptance) demands all reviewers in [the reviewer list](https://github.com/Raku/problem-solving/pull/271#reviewers) to review each proposed solution. This doesn't match reality. (I think not a single solution was accepted by means of approval of the full reviewer list.)

This is understandable, as not everyone in the reviewer list is interested in all topics and reviewing a solution does take time and energy.

There is an escape hatch in the process that allows for a PR to be accepted even without all approvals after two weeks have passed. But that's phrased to only be an escape hatch.

This mismatch of expectation and practice puts a burden on reviewers which they obviously can't mount. Also a PR submitter can interpret the lack of reviews as indifference of their work, this does have the potential to hurt their feelings.

I do not want that.

**Comment by JJ** [comment]
I don't see the escape hatch as such. It's part of the procedure. It's saying "you've got two weeks to have your say, not one day more" So I guess this is basically approval by default...

**Comment by patrickbkr** [comment]
One possible solution would be to make reviewers label specific and keep the rest of the process unchanged.

Another solution would be to accept that all PRs will have to wait two weeks before they are merged, no exceptions. Allow everyone to leave a review. Since the people on the reviewer list are then no different from someone else that has subscribed to the repo we drop the reviewer list entirely.

**Comment by patrickbkr** [comment]
> I don't see the escape hatch as such. It's part of the procedure. It's saying "you've got two weeks to have your say, not one day more" So I guess this is basically approval by default...

If that is the intention we aim for, we should rephrase the text. Currently the two week period is listed under "Edge cases and other notes". The description of the Acceptance procedure currently states:

> A review is requested from all of the reviewers (see the list).

and

> It is expected that all reviewers will understand the reasoning of the solution and in the end all of them will approve the PR.

To me this reads as a rather clear requirement.

If we go down this route and change the wording to make waiting two weeks the normal route, then we have in principle implemented _solution two_ I described in my first comment. Then we should consequently remove the reviewers list.

**Comment by vrurg** [comment]
The current approach indeed doesn't work as it must. And, aside of what @patrickbkr mentions, there are cases where approval of the label maintainer is actually sufficient and writing a solution paper with PR process is not really required. (Everybody thinks of the `language` label now.)

There is a political science opinion that laws must reflect reality, not try to bend it. Our reality is well described above: not every reviewer can handle all cases sufficiently well. So, perhaps it makes sense to adjust the problem-solving rules toward more realistic approach. Perhaps it may require minimum 3 approvals and 2 weeks approval and 4 week rejection window. So, the full procedure would be more like:

1. 13 reviews result in immediate accepatnce.
2. 3 approval with no reject mean that a PR can be merged in 2 weeks.
3. Less than 3 approval mean PR is dropped after 4 weeks.

We must find out a way to resolve cases when a disapproval is opposed to overwhelming approval rate. But here is my starting point for solution.

**Comment by codesections** [comment]
Thanks very much for raising this issue; I agree that we need to either clarify the existing process or adopt slight changes to the process.  One item that has shaped my view on the current process is the discussion that took place in #241.  In particular, one comment provided an interpretation of the existing process set out in the README:

> Also, I want to clarify something, and also make sure that you specifically understand what this process is about and how it works. Moreover, I like the shortness of the README but I wasn't direct enough when I was writing it, and as a result a lot of process details are implicitly derived from what is written indirectly. It'd be nice if you changed the README (but I'd strongly suggest to keep its length, because clearly most are not even reading what is already there). Just as an example of what I did badly, it says “If a reviewer does not respond in 14 days, they are removed from the list of reviewers on that PR.” – what this means in real life:
> 
>     * A PR is merged in 14 days if nobody rejects it
> 
>     * A PR is merged Later (after 14 days) or never if somebody does
> 
>     * Or faster if _all_ reviewers accept it, but nowadays that's unrealistic.

**Comment by nxadm** [comment]
Is the list of approvers public?

**Comment by lizmat** [comment]
@nxadm: https://github.com/raku/problem-solving#reviewers ?

**Comment by nxadm** [comment]
@lizmat: Thx!

**Comment by codesections** [comment]
I've given this matter some thought, and am generally of the opinion that we should keep the current process, but should revise the README to be more clear about what that process is.  I'm open to changing my view, but that's where I am right now.  In this comment, I plan to provide a brief explanation of why I think the current system is a good one.

But before I do, let me lay out what I understand the current system to be since – as we all seem to agree – the README isn't perfectly clear.  I understand the process to basically proceed according to this diagram:

```txt
                                                         ┌ → 4a. Speedy acceptance
1. Problem statement  → 2. Discussion  → 3. Solution PR  ┼ → 4b. Acceptance w/ consensus
                                                         ├ → 4c. Acceptance w/o consensus
                                                         └ → 4d. Rejection (no consensus) 
```

That is, the process starts when someone opens an issue, which must describe the problem without immediately proposing a solution.  Then (step 2) a period of discussion/solution formulation takes place; there's no firm length of time for this step, but it's generally best to allow some time to hear other perspective on the issue.  After some time, someone will conclude develop a solution that they think Raku should adopt, and will formally propose a solution and submit a PR (step 3).  These three steps always take place, but the forth step could be any one of the following:

If the proposed solution is unanimously supported by the [reviewers](https://github.com/Raku/problem-solving#reviewers), it's immediately adopted (4a. - Speedy acceptance).  Alternatively, if two weeks pass without any reviewer objecting and without significant evidence of non-consensus, then the solution is also adopted (4b. - Acceptance w/ consensus).  These first two paths are the normal way the Raku community makes decisions and, to my knowledge, have been the exclusive ways that PRs have been merged in this repo so far.

However, in rare cases it may be impossible to reach consensus on a decision that needs to be made.  In such cases, the RSC can [accept the PR by majority vote](https://github.com/Raku/Raku-Steering-Council/blob/main/papers/Raku_Steering_Council_Code.md) (4c. - Acceptance w/o consensus.  If the RSC declines to hold a vote on a PR that lacks consensus (or holds a vote and that vote fails to secure a majority), then the solution is rejected (4d - Rejection).

Again, the above is _not_ a new process that I'm suggesting we adopt; it's the existing process as set out in the README (and modified by the RSC Code) as I currently understand it.  I could have misread either document; if you disagree about what that process is, then that's something we can discuss.  But it's a separate conversation from what the process should be. 

---
Why do I think the process outlined above is a good one to stick with?  Well, I believe on both pragmatic and philosophical grounds that consensus is _generally_ the best way to make group decisions in a setting like this.  After all, we're all engaged in the joint process of creating an open source language.  In a real sense, Raku belongs to all of us; we all have a stake in seeing in become the best language it can be; and we all ought to have a voice in shaping its evolution.  More pragmatically, Raku is hugely dependent on volunteer contributions, and if volunteers did not have a say in the future of the language, it is hard to see how that future could be a bright one.

A couple of notes about what consensus mean: First, consensus must be _meaningful_ – if people don't know about a decision, then their failure to object doesn't represent genuine consensus.  That's why I like the idea that most PRs won't be merged for 14 days: this process means that each PR will appear in a Rakudo Weekly News published at least a week before the PR is merged.  This means that someone who follows Raku's development even casually will have the chance to share their perspective, even if they don't open the Weekly News email for a few days.

The other important point about consensus is that consensus is _not_ unanimity.  It's important that everyone have the chance to have their perspective heard, but it's equally important that one person not be able to hold up the entire process.  That would lead to gridlock and stagnation – which would be slowly terminal for any programming language, but quickly fatal for a young language like Raku.  So I'm glad that the current process significantly limits the number of people who can unilaterally prevent a solution from being adopted via consensus.

After having said all those nice things about consensus, I'm also glad that the current process allows for some decisions to be made even when consensus can't be reached.  As I've [written](https://www.codesections.com/blog/raku-manifesto/) (and [talked](https://video.fosdem.org/2021/D.perl/programming_lang_for_free_software.webm) about at length elsewhere, programming language design involves a lot of tradeoffs.  I don't think this is always the case – sometimes there's a third way [that avoids the tradeoff with sufficient cleverness](http://smallcultfollowing.com/babysteps/blog/2019/04/19/aic-adventures-in-consensus/#beyond-tradeoffs).  But at least _sometimes_, we'll need to make hard-ish decisions, and consensus won't always be possible (and trying _too_ hard to reach an impossible consensus would risk burning out our most passionate advocates).

Traditionally. the way many programming languages – including Raku – have balanced the need for consensus against the need to make hard decisions is to have a Benevolent Dictator For Life who, theoretically, can rule absolutely but who, in practice, prefers to let the community reach consensus.  Indeed, this is technically still Raku's governance model – the only distinction being that [our BDFL](http://www.wall.org/~larry/) seems highly unlikely to exercise their dictatorial powers again in this lifetime.  And the most credible claimants to the role of successor have all firmly and loudly disavowed any interest in serving as dictator, benevolent or otherwise.

Thus, in only makes sense that, in a tradition dating back at least a few millennia, in powers of the dictator devolve to a council that can, hopefully, step in just as rarely as any BDFL.

And that's the short (really, I promise!) explanation of why I'm happy with the current governance process as I understand it.  I look forward to hearing other views.

**Comment by vrurg** [comment]
@codesections thanks for detailed explanation. Except for a few minor details, I tend to agree with your view. Just my 2 cents to clarify a couple of details.

- Stage 3 is not necessarily a PR into problem-solving. A discussion might end up with a change to code, website, documentation, whatever.
- 4b doesn't really need formal reviews. In certain cases a nod from problem-solving label maintainer would be sufficient for a PR to be considered accepted. This part might cause some disagreement from those who tend to be more serious about formal procedures, but I hope it's quite understandable what we're too small community and people doesn't always have enough time for formalities.

**Comment by patrickbkr** [comment]
@codesections I agree with your view on why the current process is valuable. But unless I missed it, you did not address the problem of expectancy of all reviewers to approve a PR which I originally reported. I did understand that you value the two week review period as it gives everone a chance to notice the PR. So how would you feel about strongly deemphasizing or even removing option 4a.?  (That's what I proposed in my [first comment](https://github.com/Raku/problem-solving/issues/272#issuecomment-791390166).)

@vrurg

> - 4b doesn't really need formal reviews. In certain cases a nod from problem-solving label maintainer would be sufficient for a PR to be considered accepted. This part might cause some disagreement from those who tend to be more serious about formal procedures, but I hope it's quite understandable what we're too small community and people doesn't always have enough time for formalities.

Do I understand correctly, that you propose that the label maintainer can accept a solution without the 14-day period?
If yes, could we alternatively say that cases that are obvious enough to not require review by more people are not problem-solving worthy and are (ideally) moved out in phase 1. or 2.? As this seems to happen frequently already (issues being created for unworthy problems), we should maybe think about explicitly stating how we want to approach such issues. (Currently we usually reject and encourage the reporter to rereport explicitly naming the issue queue where the ticket should be. That seems fine.)

> 
>     1. 13 reviews result in immediate accepatnce.
>     2. 3 approval with no reject mean that a PR can be merged in 2 weeks.
>     3. Less than 3 approval mean PR is dropped after 4 weeks.
> 
> We must find out a way to resolve cases when a disapproval is opposed to overwhelming approval rate.

This bit touches on another topic: How do we want to handle rejection? I find it a bit difficult to build an opinion on how we want to handle rejection, as I think we haven't yet had a case where we rejected a PR for a non-trivial issue.

I find 3. problematic. Why do we need a rule to auto drop PRs when there wasn't a single rejection? Auto rejection has the potenial to kill fine contributions by not being looked at (PRs being neglected is something we do suffer from a lot). On the other hand I do think we should have some rule to make sure PRs are not automatically going through without anyone having had a look. ([This did happen.](https://github.com/Raku/problem-solving/pull/202))

**Comment by vrurg** [comment]
> But unless I missed it, you did not address the problem of expectancy of all reviewers to approve a PR which I originally reported.

I think you've missed it:

> Alternatively, if two weeks pass without any reviewer objecting and without significant evidence of non-consensus, then the solution is also adopted (4b. - Acceptance w/ consensus).

Consequently your question about removing 4a doesn't make sense. 4a is the way to accept a solution sooner than in 2w period. Something I don't forecast to happen any time soon... :)

> Do I understand correctly, that you propose that the label maintainer can accept a solution without the 14-day period?
> If yes, could we alternatively say that cases that are obvious enough to not require review by more people are not problem-solving worthy and are (ideally) moved out in phase 1. or 2.?

A way for an issue not to reach stage 3 is to be rejected. This is where label maintainer has the veto power. Or there is nobody to volunteer and produce a PR.

Otherwise to get an issue solved a PR must be submitted. Just, as I mentioned it above, it doesn't matter which repo it is submitted to.

It's a good question about the 14 day period though. I think in at least one case I broke this term by getting quick approval from Jonathan and submitting/merging a PR rather soon after that. Yet, we probably must avoid such practices in the future except for seldom cases when label maintainer considers a case urgent and takes the responsibility of pushing a solution through in a quick manner.



> I find 3. problematic. Why do we need a rule to auto drop PRs when there wasn't a single rejection?

I wasn't explicit on that proposal of mine, but I'm dropping it after careful consideration of all the arguments. I consider @codesections comment as almost complete solution of this issue.

**Comment by AlexDaniel** [comment]
> The process demands all reviewers in the reviewer list to review each proposed solution. This doesn't match reality. (I think not a single solution was accepted by means of approval of the full reviewer list.)
>
> […]
>
> There is an escape hatch in the process that allows for a PR to be accepted even without all approvals after two weeks have passed. But that's phrased to only be an escape hatch.

No, it's not an escape hatch. It's kinda other way around, the acceptance from all reviewers is seen as a way to fast-track solutions that really need it. But keep in mind that two weeks is not a long time, especially given that this process was designed for issues that were stuck for years.

> I don't see the escape hatch as such. It's part of the procedure. It's saying "you've got two weeks to have your say, not one day more" So I guess this is basically approval by default...

Precisely that, yes. A solution is fine unless there are objections.

Generally, @codesections gets it.

> After having said all those nice things about consensus, I'm also glad that the current process allows for some decisions to be made even when consensus can't be reached.

This part I'm not so sure about. 4c was deliberately not part of this repo. Being able to say “no” to something that breaks things for you was an intended feature of this process, and the reason people can not abuse it too much is peer pressure. Yes, this process is not like most tech-only solutions, as it balances a few things, including the fact that real human beings are involved. The existence of 4c makes consensus less likely, as people can always just throw things at RSC instead of talking to each other to understand the issues at hand and come up with a better solution.

And just to clarify, 4d is not part of the process, and again intentionally so. I'll phrase it explicitly: there is no way to reject a PR if there are still people who want to work on it. Think about it this way, if 1 defined a problem, then what would 4d reject? Definitely not the problem itself, even though this was a very common occurrence in the past (as in: we're tired of talking about this problem, let's just close the ticket). Can you reject the solution? If the solution is not good enough then iterate on it, eventually it will be accepted.

All of that worked in practice when people got to trying to rename the language for the umpteenth time, except that this time using the original process described in this repo. I have a lot less confidence in the one we have described here, with 4c and 4d added. I don't think it would've worked.


I'll also take this chance to remind people of this:

> * Assignees are allowed to call for a “shortcut” to any problem, in which case the solution is applied directly without going through the whole process.
> * Non-functional changes to existing solutions automatically go through a shortcut (typos, grammar, formatting, etc.), just submit a PR right away.
> * If a shortcut receives any criticism from the corresponding development team or other affected parties, it can be reverted and the full formal process should begin.

Again, not worded in a fantastic way, but basically, any time a change does not need a consensus, people can just apply the PR directly. If there are any objections, then you take a step back. Yep, using common sense is required here, but that shouldn't be an issue in this community.

Anyway, going back to this ticket, i think the actual issue is that the document is worded poorly and people sometimes misunderstand it. A significant amount of people understand it the way I intended it to be, so just fixing the text should resolve this ticket.

**Comment by patrickbkr** [comment]
Just to make it clear: My current understanding is, that this issue is on the RSC agenda. Am I wrong?

**Comment by lizmat** [comment]
Yes it is.  But atm things are clouded over by recent events that are currently spiraling out of control.

**Comment by AlexDaniel** [comment]
Take care. I hope all goes back to normal soon. Please ping me if more input from me is needed from me about this ticket (though it seems some of you have a good grip on it already).

**Comment by patrickbkr** [comment]
Ouch. Without any knowledge of what's up, I hope you manage to solve the situation without personal damage.

**Comment by codesections** [comment]
> Just to make it clear: My current understanding is, that this issue is on the RSC agenda. Am I wrong?

Oops, I'm pretty sure typing up a PR for this was supposed to be on my todo list, but had fallen off of it.  Thanks for the reminder!

**Comment by patrickbkr** [comment]
Closing this as the solution has been implemented.
