### ISSUE TITLE
Moving distributions between distribution backends "duplicates" them

### ISSUE THREAD

**Issue by lizmat** [Raku/problem-solving#295]
Because the Raku ecosystem allows for multiple distribution backends (currently the "old" ecosystem, CPAN (aka PAUSE) and zef), and distributions may be moved by the author from one distribution backend to another (e.g. because it is being deprecated), creates the situation that a module distribution that is identical but for the distribution backend, will appear more than once in the ecosystem.

This came up in a [raku.land](https://gitlab.com/raku-land/raku-land/-/issues/12) issue, with additional discussion on [r/rakulang](https://www.reddit.com/r/rakulang/comments/pb8z3r/insightfull_response_to_my_rakuland_question/)

**Comment by raiph** [comment]
> distributions may be moved by the author from one distribution backend to another ... creates the situation that a module distribution that is identical but for the distribution backend, will appear more than once in the ecosystem.

As I understand it this is currently indistinguishable from the two modules being different, though appearing to be identical.

For reasons I can't currently pin down rationally, I wonder if it might make sense to solve that fundamental problem first. It feels like whatever solution is designed/implemented for that might alter the nature and mechanism and consequences of any good solution to this one.

**Comment by tony-o** [comment]
Rakudo and raku should stay out of that game..the full dist str is what distinguishes the dists.  If it comes from different ecosystems with different dist strings then they should be considered different dists.  Part of the flexibility in dist naming comes with that cost and, really, people should be pinning dist versions like in other languages rather than how it's done in perl or node.  That discussion is off topic but that mindset also aids in the end user's thought process when looking for or consuming ecosystem modules.

eg,
this should be more encouraged/common: `use Dist:ver<5.0.0>:auth<zef:lizmat>`
this should be less common: `use Dist;`

**Comment by raiph** [comment]
@tony-o

Was your comment addressed to Liz (this whole issue) or my comment? I'll assume mine.

> the full dist str is what distinguishes the dists.

That makes sense to me for the notion of "identity" in the context of Rakudo / Raku as a language / zef-as-a-service-to-Raku(do), but not the notion of "identity" as in (cryptographic hash) identicality. I presume you agree with that, right?

> Rakudo and raku should stay out of that game..

I get that for Rakudo, and for "raku" *the language*, as just stated.

(But not for the focus of what I understand this repo is for, namely problem solving for Raku that's not limited to Rakudo or the Raku language, and what I understand this issue is focused on, namely the ecosystem in general and zef/fez in particular.)

**Comment by JJ** [comment]
Not totally unrelated, but I proposed in #39 to deprecate using CPAN. At the end of the day, this is also one of those fragmentation issues denounced here. Worse, you can create a distribution with the same name in a different backend, and its resolution would not be totally clear, as denounced in #229

**Comment by lizmat** [comment]
Closing this in light of #316, which would make this problem go away.
