### ISSUE TITLE
Allow "bare" indexing terms in documentation

### ISSUE THREAD

**Issue by JJ** [Raku/problem-solving#321]
Since categories (#250) were standardized, and they were implemented in the documentation source in Raku/doc#4051, it's no longer possible to simply index a term by doing `X<indexed term>`. This is due to the solution to #250 (#271) considering bare terms "categories", and the limitation of these categories, thus effectively banning "bare" words.

This is, however, a problem. Although there were only a few of these (since, in their majority, they had been provided with indexing terms *and* anchors just above where they were defined), this causes where there were before:

```raku
X<Single Argument Rule>
```

now we have

```raku
X<Single Argument Rule|Language,Single Argument Rule>
```

This causes two problems. First, there's no single source of truth for the indexing term and/or DRY, we're repeating what we have to index twice, one for what's actually rendered (left of `|`) and another for what's actually indexed (rhs of that, rhs of the comma). Second, the category it's assigned is either a judgment call or obvious: `Language`, since these are usually sections in tutorials that explain a concept (although the real difference between that category and `Reference` is not totally obvious).

So I would propose to allow these *bare* indexing terms, going forward, as well as revert changes or categories for those that were already there.

**Comment by Altai-man** [comment]
What category/categories do you suggest as being default for those?

The motivation for banning implicit categories except for headers was that prior to that decision everything "bare" was dumped into the "Reference" category, resulting in it being a bit of everything in the world, thus highly limiting any meaning in the categorization at all. Very few people cared about categories and thus everything was mindlessly thrown into "Reference".

**Comment by JJ** [comment]
Any category that's suggested as default, you can always change it by simply adding an indexing category. Repeating rendered and indexed terms is not *always* bad. It's bad when it's not possible *not* doing it.

**Comment by patrickbkr** [comment]
> It's bad when it's not possible _not_ doing it.

I think I don't understand. In what case is it not possible to write something similar to `X<Single Argument Rule|Language,Single Argument Rule>` ?

**Comment by JJ** [comment]
> > It's bad when it's not possible _not_ doing it.
> 
> I think I don't understand. In what case is it not possible to write something similar to `X<Single Argument Rule|Language,Single Argument Rule>` ?

Please read the OP.

**Comment by patrickbkr** [comment]
From what I think I understand from the OP is that not repeating is more DRY (I only partly agree, because the letters might be the same, but the semantic meaning is different.), and less typing. But neither less DRYness, nor more typing make something impossible ("not possible"). I think there is a misunderstanding somewhere. Can you please try to explain more?

**Comment by Altai-man** [comment]
>I think I don't understand. In what case is it not possible to write something similar to X<Single Argument Rule|Language,Single Argument Rule> ?

It's about not being able to just do `X<Single Argument Rule>` with some arbitrary category being assigned the writer doesn't need to think about.

So we just came from years of obscure implicit rules commanding how categorization is done, which resulted in a mess, replacing it with the simplest possible system "just write it explicitly from this list and you're good", and the suggestion is about going back to obscure implicit set of rules, justified by DRY.

**Comment by patrickbkr** [comment]
> So we just came from years of obscure implicit rules commanding how categorization is done, which resulted in a mess, replacing it with the simplest possible system "just write it explicitly from this list and you're good", and the suggestion is about going back to obscure implicit set of rules, justified by DRY.

Given this history, I currently don't think that's what JJ is proposing or there is some deeper reasoning that I'm missing. Thus my suspicion of some kind of misunderstanding and my try to clarify this.

**Comment by JJ** [comment]
@Altai-man in view of your characterization of my suggestion, I'll just  close this and refrain from doing any other suggestion regarding documentation.

**Comment by patrickbkr** [comment]
@JJ I am sad to see you go. Please consider that this is a prestressed discussion and I'm pretty sure there still is an unsolved misunderstanding still here.

@Altai-man I do understand the sentiment, but your statement is bordering a violation of the [Principle of Charity](https://en.wikipedia.org/wiki/Principle_of_charity).

**Comment by Altai-man** [comment]
@patrickbkr I am sure it is not just bordering, but can be seen as pure violation.

Here goes a wall of text mostly useless to the reader, scroll down to the last paragraph.

I do tend to get very subjective seeing how people in this community tend to oppose any changes. Even with the language name, this topic was pushed for years and the ones voting pro it were seen as aggressive and non-constructive, leading to some community members quitting, with the name being eventually changed for best or worse. It can be seen otherwise, but software needs to evolve, learn by its mistakes, and the software product not being developed is considered dead.

It is hard for me to see this being repeated again and again. Once back we had implicit categories and it resulted in a mess. Were people who caused the mess wrong or the system that allowed them to cause it wrong? My stance is people would do mistakes, even JJ, who undoubtedly knows and loves the documentation more than anyone, for years had the wrong syntax written in the CONTRIBUTING guide, not being in sync with Documentable, so blaming people won't solve the issues. Hence my desire to build a system that prevents people from doing mistakes. If implicit did not work in the past, we can try explicit and see where it goes.

>So I would propose to allow these bare indexing terms, going forward, as well as revert changes or categories for those that were already there.

This ticket suggests getting back to the implicit system that proved it being hard to use. Given I spent my time suggesting, discussing and putting the new system in place, of course I don't want for all that work to go in vain. Speaking from the technical point of view:

>First, there's no single source of truth for the indexing term and/or DRY, we're repeating what we have to index twice

Besides DRY there is AHA - avoid hasty abstractions. As I mentioned, we had abstractions for implicit categories before and it led us to mistakes.
But if it really is such an issue that causes us more harm than good, we can introduce some dead simple abstraction syntax like `X<Single Argument Rule,Language,$_>` to not type it twice. This solves the DRY note and doesn't move back to the system prone to allow mistakes again.

>Second, the category it's assigned is either a judgment call or obvious

Judgement call - yes.
Obvious - absolutely.

Categories _need_ to be obvious when you query. If you are using a search engine to shop for something, you want to see shopping items, not images or videos. If you are looking for images, you don't want to see videos or shopping items.

Categorization that is not obvious is useless to the reader and to the writer.

---

I am sure JJ cares about documentation more than anyone here and he also did put an immeasurable amount of efforts toward it being in a better thing. I remember times when `htmlify.p6` was the thing, and it wasn't extensible nor easy to understand. Heck, nobody wanted to deal with it and when people tried to do changes - it led to horrible issues occurring, because too many implicit things were going on. Not because the people doing the changes were wrong or something, but because the system was built not being easy to understand and it made the system fragile. Then JJ pushed towards Documentable and we're already in a better place. I still believe we have tickets stating it is not perfect. I don't think we would be there if his efforts were met with "No, htmlify.p6 is a simple script, why are you building something so complex instead, let's revert it and get back".

@JJ, I cannot read your mind, but I believe your aim was and is - to have a better documentation for everyone, both readers and writers. I remember you mentioning how the new system looks and feels better, so while details can vary, maybe if those of us willing to work on it can show we're heading to a better place than we originally were, you will be glad for the overall direction of the project?

**Comment by JJ** [comment]
Sorry, I'm not on board any more regarding any documentation changes, my suggestions and how they're treated. I've created a branch with the old docs, minus the category changes, and will be updating rakudocs.github.io (and/or any user domain emanating from #320)  from it from now on, cherry-picking changes from the master branch when convenient (essentially where applicable), and making changes only to that `old-docs` branch myself. Feel free to do whatever you see fit with the main branch and/or docs.raku.org.
