### ISSUE TITLE
Maybe Any:D.await should return self?

### ISSUE THREAD

**Issue by lizmat** [Raku/problem-solving#38]
Currently, it is an error to `await` on something that is not an Awaitable.  But I wonder if that makes sense.

Maybe it makes more sense to have it simply return the invocant on concrete objects?  I mean, we're already assuming that each scalar is a single element list, why not also assume that each defined value (well, maybe except for `Failure`s) is a `Promise` that has been kept.

This would make it easier to mix synchronous and asynchronous code, case in point:

    my %cache;
    method foo($bar) {
        with %cache{$bar} {
            return $_
        }
        else {
            return start { %cache{$bar} = something expensive }
        }

You could then:

        my $value = await $obj.foo("bar");

without having to know if actually a `Promise` from the `start` was returned.  And if the cached value is actually there, you wouldn't need to wrap it in a `Promise` to avoid dieing because `await` only handles something Awaitable.

Most likely I'm missing some concurrent issue that would make such an approach unwise.

**Comment by b2gills** [comment]
My only problem with this is that some people will get into the habit of spamming `await` everywhere.

**Comment by lizmat** [comment]
Then perhaps something like [Object::Delayed](https://modules.perl6.org/dist/Object::Delayed)'s `catchup` should be put in core?

**Comment by jnthn** [comment]
In terms of what's possible: the introduction of the `Awaitable` role in 6.d does mean we could potentially just pass through any non-`Awaitable`. If we did that, I don't know why we'd restrict it to defined values.

That said, the current semantics also serve a purpose: they let you know if you `await`'d something that is *not* asynchronous, but that you were expecting to be. I've had that catch the odd mistake for me.

Speaking of mistakes, the example code suggested in the issue contains a data race on `%cache`.

**Comment by lizmat** [comment]
> Speaking of mistakes, the example code suggested in the issue contains a data race on %cache.

It was inside a `monitor` of course  :-)

**Comment by jnthn** [comment]
> It was inside a monitor of course :-)

Alas, that's actually not enough, because the `start` block runs outside of the lock. The better way to do this is thus:

```
my %cache;
method foo($bar) {
    %cache{$bar} //= start { %cache{$bar} = something expensive }
}
```

Which:

1. Eliminates the code path where we don't return a `Promise`
2. Fixes the *other* race (besides violating the safety of the hash) in the original code, which could lead to starting the same expensive computation many times.

In my previous post, I almost wrote something like, "I suspect code with a sync and an async path is hard to get right", out of gut feeling that it's so. Apparently I should trust my gut more, since this example pretty much demonstrates the point. :-)
